// Business Amenities Data
export const AMENITIES = [
  'Free WiFi',
  'Parking (Free)',
  'Parking (Paid)',
  'Valet Parking',
  'Stage/Performance Area',
  'Full Bar',
  'Kitchen',
  'AV Equipment',
  'Outdoor Space',
  'Wheelchair Accessible',
  'Private Rooms',
  'Dance Floor',
  'Smoking Area',
  'Coat Check',
  'Security Onsite',
  'Kid-Friendly',
  'Pet-Friendly',
  'Pool/Hot Tub',
  'Game Room/Arcade',
  'VIP Area',
  'Bottle Service',
  'Catering Available',
  'Live Music Setup',
  'Projector/Screen',
  'Air Conditioning/Heating',
];
