// COMPREHENSIVE SERVICE LISTS FOR TOP 10 ENTREPRENEUR OCCUPATIONS
// Each occupation has 10-20 industry-standard services

export const OCCUPATION_SERVICES = {
  'DJ': [
    'Wedding DJ',
    'Birthday Party DJ',
    'Corporate Event DJ',
    'Club/Nightclub DJ',
    'Private Party DJ',
    'School Dance DJ',
    'Graduation Party DJ',
    'Bar/Bat Mitzvah DJ',
    'Sweet 16 DJ',
    'Prom DJ',
    'Radio DJ Services',
    'Mobile DJ Services',
    'DJ Equipment Rental',
    'Sound System Setup',
    'Lighting Services',
    'MC Services (with DJ)',
    'Karaoke DJ',
    'Silent Disco DJ',
  ],
  
  'Band': [
    'Wedding Band',
    'Corporate Event Band',
    'Private Party Band',
    'Festival Performance',
    'Concert Performance',
    'Bar/Restaurant Gigs',
    'Birthday Party Band',
    'Cocktail Hour Music',
    'Ceremony Music',
    'Reception Music',
    'Background Music',
    'Dance Band',
    'Cover Band Performance',
    'Original Music Performance',
    'Session Musicians',
    'Recording Services',
  ],
  
  'Photographer': [
    'Wedding Photography',
    'Engagement Photography',
    'Event Photography',
    'Corporate Event Photography',
    'Birthday Party Photography',
    'Portrait Photography',
    'Family Photography',
    'Headshot Photography',
    'Product Photography',
    'Real Estate Photography',
    'Food Photography',
    'Sports Photography',
    'Concert Photography',
    'Graduation Photography',
    'Maternity Photography',
    'Newborn Photography',
    'Photo Editing Services',
    'Photo Booth Services',
  ],
  
  'Videographer': [
    'Wedding Videography',
    'Event Videography',
    'Corporate Video Production',
    'Promotional Videos',
    'Commercial Production',
    'Music Video Production',
    'Documentary Filming',
    'Live Event Streaming',
    'Highlight Reels',
    'Drone Videography',
    'Interview Videos',
    'Social Media Content',
    'YouTube Content Creation',
    'Video Editing Services',
    'Cinematic Videos',
    'Training Videos',
  ],
  
  'Caterer': [
    'Wedding Catering',
    'Corporate Event Catering',
    'Birthday Party Catering',
    'Cocktail Party Catering',
    'Buffet Catering',
    'Plated Dinner Service',
    'Breakfast Catering',
    'Lunch Catering',
    'Dinner Catering',
    'Appetizer/Hors d\'oeuvres',
    'Dessert Catering',
    'BBQ Catering',
    'Ethnic Cuisine Catering',
    'Vegan/Vegetarian Catering',
    'Dietary Restriction Menus',
    'Staff Services',
    'Equipment Rental',
    'Drop-off Catering',
  ],
  
  'Event Planner': [
    'Full Event Planning',
    'Day-of Coordination',
    'Wedding Planning',
    'Corporate Event Planning',
    'Birthday Party Planning',
    'Anniversary Party Planning',
    'Retirement Party Planning',
    'Baby Shower Planning',
    'Bridal Shower Planning',
    'Venue Selection',
    'Vendor Coordination',
    'Budget Management',
    'Timeline Creation',
    'Theme Development',
    'Décor Planning',
    'Guest List Management',
    'RSVP Tracking',
    'Event Design',
  ],
  
  'Bartender': [
    'Wedding Bartending',
    'Private Party Bartending',
    'Corporate Event Bartending',
    'Mobile Bar Services',
    'Craft Cocktail Service',
    'Beer & Wine Service',
    'Full Bar Service',
    'Cocktail Hour Service',
    'Reception Bartending',
    'Mixology Classes',
    'Signature Cocktail Creation',
    'Bar Setup & Breakdown',
    'Glassware Rental',
    'Bar Equipment Rental',
    'Non-Alcoholic Mocktails',
    'Bartender Training',
  ],
  
  'Mixologist': [
    'Wedding Cocktail Service',
    'Private Party Mixology',
    'Corporate Event Cocktails',
    'Craft Cocktail Creation',
    'Signature Drink Development',
    'Cocktail Menu Design',
    'Molecular Mixology',
    'Themed Cocktail Bars',
    'Tasting Events',
    'Mixology Classes',
    'Bar Consulting',
    'Recipe Development',
    'Premium Spirit Service',
    'Seasonal Cocktail Menus',
  ],
  
  'MC/Host': [
    'Wedding MC',
    'Corporate Event Host',
    'Awards Ceremony Host',
    'Gala Host',
    'Fundraiser Host',
    'Conference MC',
    'Panel Moderator',
    'Auction Host',
    'Birthday Party Host',
    'Game Show Host',
    'Trivia Night Host',
    'Karaoke Host',
    'Event Opening/Closing',
    'Introductions & Announcements',
    'Crowd Engagement',
    'Script Writing',
  ],
  
  'Dancer': [
    'Wedding Dance Performance',
    'Corporate Event Performance',
    'Private Party Performance',
    'Choreography Services',
    'Dance Instruction',
    'First Dance Lessons',
    'Group Dance Lessons',
    'Flash Mob Choreography',
    'Cultural Dance Performance',
    'Contemporary Dance',
    'Hip Hop Performance',
    'Ballet Performance',
    'Jazz Dance',
    'Latin Dance',
    'Ballroom Dance',
    'Dance Troupe Performance',
  ],
  
  'Choreographer': [
    'Wedding Choreography',
    'Music Video Choreography',
    'Stage Show Choreography',
    'Dance Routine Creation',
    'Group Choreography',
    'Solo Choreography',
    'Corporate Event Choreography',
    'Flash Mob Choreography',
    'Competition Choreography',
    'Recital Choreography',
    'Theater Choreography',
    'Dance Class Instruction',
    'Private Lessons',
    'Virtual Choreography',
  ],
  
  'Comedian': [
    'Stand-Up Comedy',
    'Corporate Event Comedy',
    'Private Party Entertainment',
    'Wedding Entertainment',
    'Roast Services',
    'Clean Comedy Sets',
    'Adult Comedy Sets',
    'MC & Comedy Combo',
    'Virtual Comedy Shows',
    'Comedy Writing',
    'Improv Comedy',
    'Sketch Comedy',
    'Comedy Consulting',
    'Entertainment Booking',
  ],
  
  'Content Creator': [
    'Social Media Content',
    'Instagram Content Creation',
    'TikTok Content Creation',
    'YouTube Content Creation',
    'Facebook Content',
    'Brand Content Creation',
    'Sponsored Content',
    'Product Photography',
    'Product Videography',
    'Influencer Campaigns',
    'Content Strategy',
    'Caption Writing',
    'Hashtag Strategy',
    'Social Media Management',
    'Reel & Short-Form Video',
    'Story Content',
    'Blog Content',
    'Email Content',
    'Brand Partnerships',
    'User-Generated Content',
  ],
  
  'Graphic Designer': [
    'Logo Design',
    'Brand Identity Design',
    'Social Media Graphics',
    'Event Flyer Design',
    'Poster Design',
    'Business Card Design',
    'Brochure Design',
    'Menu Design',
    'Invitation Design',
    'Banner Design',
    'T-Shirt Design',
    'Packaging Design',
    'Infographic Design',
    'Album Cover Design',
    'Website Graphics',
    'Print Design',
    'Marketing Materials',
  ],
  
  'Singer': [
    'Wedding Ceremony Performance',
    'Wedding Reception Performance',
    'Corporate Event Performance',
    'Private Party Performance',
    'Birthday Party Performance',
    'Concert Performance',
    'Bar/Restaurant Gigs',
    'National Anthem Performance',
    'Cocktail Hour Music',
    'Background Music',
    'Acoustic Sets',
    'Studio Recording',
    'Demo Recording',
    'Vocal Lessons',
  ],
  
  'Musical Artist': [
    'Live Performance',
    'Concert Performance',
    'Festival Performance',
    'Private Event Performance',
    'Wedding Performance',
    'Corporate Event Performance',
    'Studio Recording',
    'Music Production',
    'Song Writing',
    'Music Composition',
    'Album Recording',
    'Demo Recording',
    'Music Lessons',
    'Session Work',
  ],
  
  'Rapper': [
    'Live Performance',
    'Concert Performance',
    'Festival Performance',
    'Private Event Performance',
    'Club Performance',
    'Studio Recording',
    'Mixtape Recording',
    'Album Recording',
    'Demo Recording',
    'Feature Verses',
    'Music Video Appearance',
    'Songwriting',
    'Freestyle Sessions',
    'Music Production',
  ],

  'Hair Stylist': [
    'Wedding Hair Styling',
    'Bridal Hair',
    'Prom Hair Styling',
    'Special Event Hair',
    'Photo Shoot Hair',
    'Fashion Show Hair',
    'Hair & Makeup Combo',
    'Updo Styling',
    'Hair Extensions',
    'Braiding Services',
    'Party Hair Styling',
    'Formal Event Hair',
    'On-Location Hair Services',
    'Group Hair Styling',
  ],

  'Makeup Artist': [
    'Wedding Makeup',
    'Bridal Makeup',
    'Prom Makeup',
    'Special Event Makeup',
    'Photo Shoot Makeup',
    'Fashion Show Makeup',
    'Hair & Makeup Combo',
    'Airbrush Makeup',
    'Natural Makeup',
    'Glamour Makeup',
    'Party Makeup',
    'Formal Event Makeup',
    'On-Location Makeup Services',
    'Group Makeup Services',
    'Makeup Lessons',
  ],
  
  'Event Promoter': [
    'Nightclub Event Promotion',
    'Concert Promotion',
    'Festival Promotion',
    'Party Promotion',
    'Social Media Marketing',
    'Flyer Design & Distribution',
    'Street Team Management',
    'Influencer Outreach',
    'Email Marketing Campaigns',
    'Event Ticketing Management',
    'VIP List Management',
    'Door/Guest List Services',
    'Radio Promotion',
    'Press Release Writing',
    'Media Kit Creation',
    'Sponsorship Acquisition',
    'Brand Partnership Development',
    'Event Analytics & Reporting',
  ],
  
  'Promoter': [
    'Nightclub Event Promotion',
    'Concert Promotion',
    'Festival Promotion',
    'Party Promotion',
    'Social Media Marketing',
    'Flyer Design & Distribution',
    'Street Team Management',
    'Influencer Outreach',
    'Email Marketing Campaigns',
    'Event Ticketing Management',
    'VIP List Management',
    'Door/Guest List Services',
    'Radio Promotion',
    'Press Release Writing',
    'Media Kit Creation',
    'Sponsorship Acquisition',
    'Brand Partnership Development',
    'Event Analytics & Reporting',
  ],
  
  'Social Media Manager': [
    'Social Media Strategy',
    'Content Calendar Planning',
    'Instagram Management',
    'Facebook Management',
    'TikTok Management',
    'Twitter/X Management',
    'LinkedIn Management',
    'Social Media Advertising',
    'Influencer Partnerships',
    'Community Management',
    'Analytics & Reporting',
    'Content Creation',
    'Hashtag Strategy',
    'Engagement Growth',
    'Brand Voice Development',
  ],
  
  'Marketing Consultant': [
    'Marketing Strategy Development',
    'Brand Strategy',
    'Market Research',
    'Competitive Analysis',
    'Target Audience Analysis',
    'Marketing Plan Creation',
    'Digital Marketing Strategy',
    'Content Marketing Strategy',
    'SEO Strategy',
    'Email Marketing',
    'Marketing Analytics',
    'Campaign Management',
    'Brand Positioning',
    'Go-to-Market Strategy',
  ],
  
  'PR Specialist': [
    'Press Release Writing',
    'Media Outreach',
    'Press Kit Creation',
    'Media Relations',
    'Crisis Communication',
    'Brand Reputation Management',
    'Event PR',
    'Launch Campaigns',
    'Interview Preparation',
    'Spokesperson Training',
    'Media Monitoring',
    'Influencer Relations',
    'Public Speaking Coaching',
  ],
  
  'Influencer': [
    'Sponsored Posts',
    'Brand Partnerships',
    'Product Reviews',
    'Event Appearances',
    'Brand Ambassador Programs',
    'Social Media Takeovers',
    'Unboxing Videos',
    'Tutorial Content',
    'Affiliate Marketing',
    'Meet & Greets',
    'Live Streaming',
    'Content Collaborations',
  ],
  
  'Brand Ambassador': [
    'Event Representation',
    'Product Demonstrations',
    'Trade Show Staffing',
    'Promotional Events',
    'Sampling Programs',
    'Street Team Activation',
    'Retail Promotions',
    'Social Media Advocacy',
    'Content Creation',
    'Brand Awareness Campaigns',
  ],
  
  'Audio Engineer': [
    'Live Sound Engineering',
    'Studio Recording',
    'Mixing Services',
    'Mastering Services',
    'Sound Design',
    'Music Production',
    'Podcast Recording',
    'Voice-Over Recording',
    'Audio Editing',
    'Live Event Sound',
    'Sound System Setup',
    'Acoustic Treatment',
  ],
  
  'Stage Manager': [
    'Live Event Stage Management',
    'Theater Stage Management',
    'Concert Stage Management',
    'Festival Coordination',
    'Rehearsal Management',
    'Cue Calling',
    'Technical Coordination',
    'Crew Management',
    'Safety Compliance',
    'Production Scheduling',
  ],
  
  'Event Decorator': [
    'Wedding Decorations',
    'Birthday Party Decorations',
    'Corporate Event Decor',
    'Balloon Decorations',
    'Floral Arrangements',
    'Centerpiece Design',
    'Backdrop Design',
    'Lighting Design',
    'Table Settings',
    'Theme Decorations',
    'DIY Decor Workshops',
  ],
  
  'Lighting Technician': [
    'Stage Lighting',
    'Event Lighting Design',
    'Architectural Lighting',
    'Concert Lighting',
    'Wedding Lighting',
    'Uplighting Services',
    'LED Lighting',
    'Moving Light Programming',
    'Lighting Equipment Rental',
    'Installation Services',
  ],
  
  'Sound Technician': [
    'Live Sound Setup',
    'PA System Rental',
    'Microphone Setup',
    'Sound Check Services',
    'Audio Troubleshooting',
    'Monitor Setup',
    'Wireless Systems',
    'Sound System Installation',
    'Equipment Maintenance',
  ],
  
  'AV Specialist': [
    'Full AV Production',
    'Video Projection',
    'Screen Rental & Setup',
    'Conference AV',
    'Presentation Support',
    'Live Streaming Setup',
    'Hybrid Event Technology',
    'Video Conferencing',
    'Interactive Displays',
  ],
  
  'Security Personnel': [
    'Event Security',
    'Venue Security',
    'VIP Protection',
    'Crowd Control',
    'Door Security',
    'Parking Security',
    'Loss Prevention',
    'Emergency Response',
  ],
  
  'Event Staff': [
    'Event Setup',
    'Event Breakdown',
    'Registration Staff',
    'Hospitality Staff',
    'Coat Check Services',
    'Ushering Services',
    'General Event Support',
  ],
  
  'Venue Manager': [
    'Venue Operations',
    'Event Coordination',
    'Vendor Management',
    'Client Relations',
    'Space Planning',
    'Event Logistics',
    'Staff Supervision',
  ],
  
  'Wedding Planner': [
    'Full Wedding Planning',
    'Partial Wedding Planning',
    'Month-of Coordination',
    'Vendor Coordination',
    'Timeline Creation',
    'Budget Management',
    'Venue Selection',
    'Design & Styling',
    'Rehearsal Coordination',
    'Day-of Coordination',
  ],
  
  'Party Planner': [
    'Birthday Party Planning',
    'Anniversary Planning',
    'Retirement Party Planning',
    'Baby Shower Planning',
    'Bridal Shower Planning',
    'Theme Party Planning',
    'Kids Party Planning',
    'Sweet 16 Planning',
    'Quinceañera Planning',
  ],
  
  'Personal Chef': [
    'Private Dining Experiences',
    'Meal Prep Services',
    'In-Home Cooking',
    'Dinner Parties',
    'Cooking Classes',
    'Menu Planning',
    'Special Diet Meals',
    'Date Night Dinners',
  ],
  
  'Food Truck Operator': [
    'Event Catering',
    'Private Party Service',
    'Corporate Lunch Service',
    'Wedding Reception',
    'Festival Vending',
    'On-Site Cooking',
  ],
  
  'Baker/Pastry Chef': [
    'Wedding Cakes',
    'Birthday Cakes',
    'Custom Cakes',
    'Cupcakes',
    'Cookies',
    'Pastries',
    'Dessert Tables',
    'Specialty Desserts',
  ],
  
  'Sommelier': [
    'Wine Pairing',
    'Wine Tasting Events',
    'Wine Education',
    'Cellar Management',
    'Wine Selection Consulting',
  ],
  
  'Wait Staff': [
    'Event Serving',
    'Bartending Support',
    'Buffet Service',
    'Plated Dinner Service',
    'Cocktail Service',
  ],
  
  'Actor': [
    'Theater Performance',
    'Film Acting',
    'Commercial Acting',
    'Voice Acting',
    'Character Performances',
    'Event Entertainment',
  ],
  
  'Magician': [
    'Close-Up Magic',
    'Stage Magic',
    'Birthday Party Magic',
    'Corporate Magic Shows',
    'Wedding Entertainment',
    'Magic Lessons',
  ],
  
  'Circus Performer': [
    'Acrobatics',
    'Juggling',
    'Fire Performance',
    'Aerial Acts',
    'Stilt Walking',
    'Clown Entertainment',
  ],
};


// Helper function to get services for a given occupation
export function getServicesForOccupation(occupation: string): string[] {
  // Handle legacy occupation names with fallback
  let normalizedOccupation = occupation;
  
  // Map legacy/incorrect occupation names to correct ones
  const occupationMappings: { [key: string]: string } = {
    'Photographer (Marketing)': 'Photographer',
    'Videographer (Marketing)': 'Videographer',
    'Video Producer': 'Videographer', // Video Producer uses Videographer services
    // Add more mappings as needed
  };
  
  if (occupationMappings[occupation]) {
    normalizedOccupation = occupationMappings[occupation];
  }
  
  return OCCUPATION_SERVICES[normalizedOccupation] || [];
}

// Get all supported occupations
export function getSupportedOccupations(): string[] {
  return Object.keys(OCCUPATION_SERVICES).sort();
}

// Check if an occupation has predefined services
export function hasServicesForOccupation(occupation: string): boolean {
  // Handle legacy occupation names
  const occupationMappings: { [key: string]: string } = {
    'Photographer (Marketing)': 'Photographer',
    'Videographer (Marketing)': 'Videographer',
    'Video Producer': 'Videographer', // Video Producer uses Videographer services
  };
  
  const normalizedOccupation = occupationMappings[occupation] || occupation;
  return normalizedOccupation in OCCUPATION_SERVICES;
}
