export const EVENT_CATEGORIES = [
  'DJ Nights',
  'Live Bands & Concerts',
  'Dance Parties',
  'Karaoke',
  'Comedy Shows',
  'Open Mic Nights',
  'Themed Parties',
  'Ladies Night',
  'Trivia Nights',
  'Game Nights',
  'Food & Drink Events',
  'Wine Tastings',
  'Beer Festivals',
  'Art Exhibitions',
  'Fashion Shows',
  'Cultural Events',
  'Community Volunteer Nights',
  'Workshops & Classes',
  'Networking Events',
  'Family-Friendly Events',
  'Outdoor Festivals',
  'Sports Viewing Parties',
  'Pool Parties',
  'Brunch Events',
  'Holiday Parties',
  'Block Parties',
  'Raffles & Giveaways',
  'Special Events',
  'Private Events',
  'Birthday Parties',
  'Corporate Events',
  'After Hours',
  'Magic Shows',
  'Poetry Slams',
  'Silent Disco',
  'Talent Shows',
  'Movie Nights',
  'Car Shows',
  'Vendor Markets',
  'Health & Wellness Events',
  'Fitness Classes',
  'Kids Activities',
  'Pet-Friendly Events',
  'Fundraisers & Charity Events',
  'Graduation Parties',
  'School Events',
  'Anniversary Parties',
  'Bachelor/Bachelorette Parties',
  'Launch Parties',
  'Pop-Up Shops',
  'Other',
].sort();
