// COMPREHENSIVE Master List of Entrepreneur Services
// Covers all roles in the entertainment industry - 145+ categories
// Multi-select format with "Other" options for each category
// ALL SERVICES SORTED ALPHABETICALLY WITHIN EACH CATEGORY

export interface ServiceCategory {
  category: string;
  services: string[];
}

export const ENTREPRENEUR_SERVICES: ServiceCategory[] = [
  {
    category: '⛺ Event Support',
    services: [
      'AV Equipment Rental',
      'Accessibility Coordinator',
      'Babysitting/Childcare',
      'Backline Provider',
      'Cleaning Crew/Event Cleanup',
      'Coat Check Attendant',
      'Crowd Control Specialist',
      'Environmental/Sustainability Services',
      'Event Decorator/Florist',
      'Event Host/Emcee',
      'Event Insurance Provider',
      'Event Planner/Coordinator',
      'Event Staffing Agency',
      'First Aid/Medical Services',
      'Green Room Attendant',
      'Guest List Manager',
      'Hair Stylist',
      'Hospitality/Guest Services',
      'Lighting Technician/Designer',
      'Live Stream Technician',
      'Locker/Storage Manager',
      'Lost & Found Attendant',
      'Maintenance/Facility Services',
      'Makeup Artist',
      'Merchandise Vendor',
      'Other - Event Support',
      'Parking Attendant',
      'Personal Assistant',
      'Pet Care/Animal Handler',
      'Photographer',
      'Rental Services (tables, chairs, tents)',
      'Runner/Errand Services',
      'Security/Event Guard',
      'Set Designer/Stage Decorator',
      'Sound Engineer/Audio Tech',
      'Stage Manager',
      'Stagehand/Roadie',
      'Ticketing/Box Office',
      'Transportation/Shuttle Service',
      'Valet Service',
      'Video Technician/Projectionist',
      'Videographer',
      'Volunteer Coordinator',
      'Wardrobe/Costume Designer'
    ].sort(),
  },
  {
    category: '🍔 Food & Drink Support',
    services: [
      'Baker/Pastry Chef',
      'Barista/Coffee Service',
      'Bartender',
      'Beverage Vendor',
      'Caterer',
      'Concession Stand Operator',
      'Dessert/Sweets Vendor',
      'Food Truck/Cart Vendor',
      'Gluten-Free Specialist',
      'Mixologist/Cocktail Specialist',
      'Mobile Bar Service',
      'Nutritionist/Dietary Consultant',
      'Other - Food & Drink Support',
      'Private Chef',
      'Server/Wait Staff',
      'Sommelier',
      'Vegan/Vegetarian Specialist',
      'Wine/Beer/Spirits Vendor'
    ].sort(),
  },
  {
    category: '🎤 Occupation',
    services: [
      'A Cappella Group',
      'Acrobat',
      'Actor/Actress',
      'Aerialist',
      'Alternative Band',
      'Arranger',
      'Auctioneer',
      'Ballet Dancer',
      'Booking Agent/Manager',
      'Ballroom Dancer',
      'Band Leader',
      'Bassist',
      'Beatmaker',
      'Big Band',
      'Bluegrass Band',
      'Blues Artist',
      'Blues Band',
      'Body Painter',
      'Brass Band',
      'Burlesque Performer',
      'Cabaret Artist',
      'Caricature Artist',
      'Cellist',
      'Chamber Orchestra',
      'Choir',
      'Choir Director',
      'Choreographer',
      'Circus Performer',
      'Clarinetist',
      'Classical Artist',
      'Club DJ',
      'Comedian/Stand-Up',
      'Composer/Songwriter',
      'Contemporary/Modern Dancer',
      'Contortionist',
      'Corporate Event Band',
      'Country Artist',
      'Country Band',
      'Cover Band',
      'DJ',
      'Dance Band',
      'Dance Crew/Team',
      'Dance Instructor',
      'Dancer (General)',
      'Drag Performer',
      'Drum Line',
      'Drummer/Percussionist',
      'Electronic Music Producer',
      'Electronic/EDM Artist',
      'Electronic/EDM Group',
      'Event Band',
      'Event DJ',
      'Event Emcee',
      'Face Painter',
      'Fire Performer',
      'Flutist',
      'Folk Band',
      'Folk/Acoustic Artist',
      'Game Show Host',
      'Gospel Artist',
      'Gospel Band',
      'Gospel Choir',
      'Guitarist',
      'Harpist',
      'Hip-Hop Dancer',
      'Host/MC',
      'Improv Performer',
      'Indie Band',
      'Jazz Artist',
      'Jazz Band',
      'Jazz Ensemble',
      'Juggler',
      'Karaoke Host',
      'Latin Artist',
      'Latin Band',
      'Latin Dancer',
      'Lyricist',
      'Magician/Illusionist',
      'Marching Band',
      'Mentalist',
      'Metal Band',
      'Mime Artist',
      'Mobile DJ',
      'Model',
      'Music Director',
      'Music Educator/Instructor',
      'Music Producer',
      'Music Therapist',
      'Opera Singer',
      'Orchestra',
      'Orchestra Conductor',
      'Other - Entertainment',
      'Party Band',
      'Pianist/Keyboardist',
      'Pop Artist',
      'Pop Band',
      'Punk Band',
      'Puppeteer',
      'R&B Artist',
      'R&B Band',
      'Radio DJ',
      'Rapper/Hip-Hop Artist',
      'Reggae Artist',
      'Reggae Band',
      'Rock Artist',
      'Rock Band',
      'Saxophonist',
      'Show Band',
      'Singer/Vocalist',
      'Solo Instrumentalist',
      'Soul Artist',
      'Soul Band',
      'Specialty Entertainer',
      'Spoken Word Artist/Poet',
      'Steel Drum Player',
      'Stilt Walker',
      'String Quartet',
      'Stunt Performer',
      'Stylist (Fashion/Wardrobe)',
      'Symphony Orchestra',
      'Tap Dancer',
      'Theater Performer',
      'Tribute Band',
      'Trombonist',
      'Trumpeter',
      'Variety Band',
      'Ventriloquist',
      'Violinist',
      'Visual Artist (Live Painting, Graffiti)',
      'Vocal Coach',
      'Wedding Band',
      'Wedding DJ'
    ].sort(),
  },
  {
    category: '📣 Marketing & Promotion',
    services: [
      'Blogger/Vlogger',
      'Community Outreach Coordinator',
      'Content Creator (Photo/Video)',
      'Digital Ad Specialist',
      'Email Marketing Coordinator',
      'Event Publicist',
      'Flyer Distribution',
      'Graphic Designer',
      'Influencer/Brand Ambassador',
      'Marketing Consultant',
      'Other - Marketing & Promotion',
      'PR/Media Relations',
      'Press Writer/Journalist',
      'Radio/Podcast Host',
      'SEO Specialist',
      'Social Media Marketing',
      'Sponsorship Manager',
      'Street Team/Promoter',
      'TV Host/Producer',
      'Website Designer'
    ].sort(),
  }
].sort((a, b) => a.category.localeCompare(b.category));

// Flatten all services for search/filter purposes
export const ALL_SERVICES = ENTREPRENEUR_SERVICES.flatMap(cat => cat.services).sort();
